### ISSUE TITLE
Please create a .gitignore file

### ISSUE THREAD

**Issue by moony-chen** [LukePerficient/KYT#1]
We'd like to ignore certain files to be checked into git repo, such as .DS_Store. You can search for one that is commonly used for iOS project.

**Comment by LukePerficient** [comment]
Hey Moony,
Got the message, just wanted to verify you guys could access it

**Comment by Duskamo** [comment]
@moony-chen I used a common iOS .gitignore file found here https://github.com/github/gitignore/blob/master/Objective-C.gitignore.

Is this one good enough?

Commit #: cf33bd6ce73a8a20db7410ff2fc90eaf9cdef2ec

**Comment by MarkShenT** [comment]
yes, this one is good.
Usually, we will also add .DS_Store, as it is the system generated file, has nothing to do with our code.

**Comment by moony-chen** [comment]
yes, this one is good.
Usually, we will also add .DS_Store, as it is the system generated file, has nothing to do with our code.
