### ISSUE TITLE
Please resolve the KYTTeamMemberViewCell.h issue

### ISSUE THREAD

**Issue by MarkShenT** [LukePerficient/KYT#2]
<img width="766" alt="screen shot 2017-09-13 at 12 53 28 pm" src="https://user-images.githubusercontent.com/29293383/30360258-e659c924-9882-11e7-8349-850b853a582a.png">

**Comment by LukePerficient** [comment]
Issue #2 resolved.

**Comment by MarkShenT** [comment]
confirmed, close it
