### ISSUE TITLE
containsSpecialCharacters does not work well

### ISSUE THREAD

**Issue by MarkShenT** [LukePerficient/KYT#3]
<img width="376" alt="screen shot 2017-09-13 at 1 54 53 pm" src="https://user-images.githubusercontent.com/29293383/30361728-2bd04c50-988b-11e7-90e7-4287ea8c675b.png">

See the attached image, propose to notify user cannot include special characters instead of doing nothing

**Comment by LukePerficient** [comment]
Fixed the last name special character bug
ef8bca0a0866ff66651f6445cfc34916d6f1cb8a

**Comment by LukePerficient** [comment]
Updated fix to include empty string and clean up code.
91a7f2da77ff3ad2e6ebc42e32343283bf092cb9

**Comment by MarkShenT** [comment]
confirmed
