### ISSUE TITLE
Please update the storyboard

### ISSUE THREAD

**Issue by MarkShenT** [LukePerficient/KYT#5]
<img width="966" alt="screen shot 2017-09-13 at 2 09 05 pm" src="https://user-images.githubusercontent.com/29293383/30362150-3335f2ae-988d-11e7-92c8-4e3e2db6a704.png">

The navigation controller between two VCs  is un-necessary, please remove it and try either push or present directly to the "Member Add" VC

**Comment by Duskamo** [comment]
Resolved in commit 7b6903795e870c3b732af6bf399557df97dcd980.

**Comment by MarkShenT** [comment]
confirmed, close it
