### ISSUE TITLE
Method naming

### ISSUE THREAD

**Issue by MarkShenT** [LukePerficient/KYT#6]
We usually start parameter label with lower case letter
![image](https://user-images.githubusercontent.com/29293383/30364826-660bda3a-9898-11e7-881a-f2bad0d4872c.png)
![image](https://user-images.githubusercontent.com/29293383/30364846-78189100-9898-11e7-83d6-ef97af4f0d8d.png)

**Comment by Duskamo** [comment]
Resolved, will push to repository tomorrow on 9/19. Will post another comment with commit id.

**Comment by Duskamo** [comment]
Can view the latest commit f17e0d7cbacadd8d589b77d2c0b380a4bddab9d7 for checking resolved issue.

**Comment by MarkShenT** [comment]
fixed, thx
