### ISSUE TITLE
On Memeber Add, touch anywhere will bring up the photo picker

### ISSUE THREAD

**Issue by MarkShenT** [LukePerficient/KYT#7]
Even on the first/last name label

**Comment by Duskamo** [comment]
Might be indirectly resolved. Could you guys take a quick look at this one again?

Can view the latest commit f17e0d7cbacadd8d589b77d2c0b380a4bddab9d7 for checking resolved issue.

**Comment by MarkShenT** [comment]
confirm resolved, thx
