### ISSUE TITLE
KYTTeamMemberSpec.mm

### ISSUE THREAD

**Issue by moony-chen** [LukePerficient/KYT#8]
`member = [[KYTTeamMember alloc] init];` is not very useful in `beforeEach`, as in every `it`, member will be assigned to another object
Similar problem in KYTTeamMemberModelTests.m,
`self.member` is not used anywhere

**Comment by Duskamo** [comment]
Resolved, will push to repository tomorrow on 9/19. Will post another comment with commit id.

**Comment by Duskamo** [comment]
Can view the latest commit f17e0d7cbacadd8d589b77d2c0b380a4bddab9d7 for checking resolved issue.
