### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by moony-chen** [LukePerficient/KYT#9]
Retain cycle is the most common form of memory leak, please check your delegate implementation.
Instruments have a tool to detect leaks, see screenshot below, you can see the ImageSelectorDelegate and MemberViewController both have 7 instances, after I added member 7 times.
<img width="665" alt="screen shot 2017-09-15 at 11 20 12 am" src="https://user-images.githubusercontent.com/6201747/30466635-de808a36-9a11-11e7-9d6f-e9fe95bd8f62.png">

**Comment by Duskamo** [comment]
Resolved and ready to be checked.

Commit #: 88f70a9941f50768401a58b21f1ec809e37a4873
Branch: Bug_MemoryLeak

**Comment by moony-chen** [comment]
Hi @Duskamo , it should be the other commit you changed **weak** solved the issue:
```@property (nonatomic, weak) UIViewController<ImageSelector> *viewController;```
without it, the dealloc would not even be called.
And we usually override dealloc to free some external resources, not the ivar, as recommended by document
